### ISSUE TITLE
AGO module should work outside of AWS batch

### ISSUE THREAD

**Issue by Alexander-M-Waldman** [CityOfPhiladelphia/databridge-etl-tools#20]
https://github.com/CityOfPhiladelphia/databridge-etl-tools/blob/7ad3b58c0ac7ce2a8dff52226577990f02ee0268/databridge_etl_tools/ago.py#L67

**Comment by floptical** [comment]
Addressed here: https://github.com/CityOfPhiladelphia/databridge-etl-tools/commit/b9f9d7d4ea6791129796f82a9224c80dff397025
